[build]
  # 建置指令
  command = "npm run build"
  # 發布目錄
  publish = "dist"

# API 代理：將所有 /api/* 請求重定向到 Railway API
[[redirects]]
  from = "/api/*"
  to = "https://jadeapi-production.up.railway.app/api/:splat"
  status = 200
  force = true

# 處理 Vue Router 的歷史模式 (History Mode)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 環境變數設定
[build.environment]
  NODE_VERSION = "18"
  VUE_APP_API_URL = "https://jadeapi-production.up.railway.app"
  VUE_APP_API_BASE_URL = "https://jadeapi-production.up.railway.app"
  VUE_APP_CLOUDINARY_URL = "https://res.cloudinary.com/jadetainan"
  VUE_APP_CLOUDINARY_CLOUD_NAME = "jadetainan"
  VUE_APP_CLOUDINARY_API_KEY = "384776688611428"
  VUE_APP_CLOUDINARY_UPLOAD_PRESET = "jade-products"
  VUE_APP_TITLE = "JADE 電商管理系統"
  VUE_APP_VERSION = "1.0.0"
  VUE_APP_DEBUG = "false"
  VUE_APP_LOG_LEVEL = "error"
  VUE_APP_ECPAY_STAGE = "false"

# 快取設定
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
