[build]
  # 建置指令
  command = "npm run build"
  # 發布目錄
  publish = "dist"

# 處理 Vue Router 的歷史模式 (History Mode)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 環境變數設定 (如果需要)
[build.environment]
  NODE_VERSION = "18"

# 快取設定
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
